name: c001apk_flutter
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: '>=3.22.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  android_intent_plus: ^5.1.0
  bcrypt: ^1.1.3
  cached_network_image: ^3.4.0
  chat_bottom_container: ^0.2.0
  #  flutter_platform_utils: ^1.0.0
  connectivity_plus:
    path: "../flutter_packages/flutter_plus_plugins/packages/connectivity_plus/connectivity_plus/"
  crypto: ^3.0.3
  cupertino_icons:
    path: "../flutter_packages/flutter_packages/third_party/packages/cupertino_icons/"
  device_info_plus:
    path: "../flutter_packages/flutter_plus_plugins/packages/device_info_plus/device_info_plus/"
  dio: ^5.5.0+1
  dynamic_color: ^1.7.0
  expandable_page_view: ^1.0.17
  extended_nested_scroll_view: ^6.2.1
  file_picker:
    path: "../flutter_packages/fluttertpc_file_picker/"
  flutter_inappwebview:
    path: "../flutter_packages/flutter_inappwebview/flutter_inappwebview/"
  flutter_smart_dialog: ^4.9.7+9
  flutter_widget_from_html_core:
    path: "../flutter_packages/flutter_widget_from_html/packages/core/"
  get:
    path: "../flutter_packages/mypkg/getx/"
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  html: ^0.15.4
  image_picker:
    path: "../flutter_packages/flutter_packages/packages/image_picker/image_picker"
  indent: ^2.0.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  mime: ^1.0.5
  modal_bottom_sheet:
    path: "../flutter_packages/modal_bottom_sheet/modal_bottom_sheet"
  package_info_plus:
    path: "../flutter_packages/flutter_plus_plugins/packages/package_info_plus/package_info_plus/"
  path_provider: ^2.1.4
  permission_handler:
    path: "../flutter_packages/flutter_permission_handler/permission_handler/"
  photo_view: ^0.15.0
  gallery_saver:
    path: "../flutter_packages/fluttertpc_gallery_saver/"
  share_plus:
    path: "../flutter_packages/flutter_plus_plugins/packages/share_plus/share_plus/"
  url_launcher:
    path: "../flutter_packages/flutter_packages/packages/url_launcher/url_launcher"
  uuid: ^4.4.2
  window_manager: ^0.4.0
  xml: ^6.5.0

dependency_overrides:
  path_provider:
    path: "../flutter_packages/flutter_packages/packages/path_provider/path_provider"

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  build_runner: ^2.4.10
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
  flutter_native_splash:
    path: "../flutter_packages/fluttertpc_flutter_native_splash/"
  hive_generator: ^2.0.1
  pigeon:
    path: "../flutter_packages/flutter_packages/packages/pigeon"
#    git:
#      url: "https://gitee.com/openharmony-sig/flutter_packages.git"
#      path: "packages/pigeon"

flutter_launcher_icons:
  android: true
  ios: true
  ohos: true
  remove_alpha_ios: true
  image_path: assets/icon/icon.png
  image_path_ios: assets/icon/icon.png
  image_path_ohos: assets/icon/icon.png
  macos:
    generate: true
    image_path: assets/icon/icon.png
  windows:
    generate: true
    image_path: assets/icon/icon.png
  web:
    generate: true
    image_path: assets/icon/icon.png


flutter_native_splash:
  android_12:
    color: "#ffffff"
    color_dark: "#212121"
  color: "#ffffff"
  color_dark: "#212121"
  image: assets/icon/icon-splash.png
  image_dark: assets/icon/icon-splash.png

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/emojis/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
